# Generated by Django 4.0.1 on 2022-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unsolved', 'Нерешенный'), ('solved', 'Решенный'), ('frozen', 'Заморожен')], default='unsolved', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
