# Generated by Django 4.0.1 on 2022-01-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
