# Generated by Django 4.0.1 on 2022-01-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0017_alter_message_text_alter_message_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_message',
            new_name='created',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
