# Generated by Django 4.0.1 on 2022-01-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_rename_date_message_message_created_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
    ]
