# Generated by Django 4.0.1 on 2022-01-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_rename_user_message_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='owner',
        ),
    ]
