# Generated by Django 4.0.1 on 2022-01-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_rename_user_ticket_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created']},
        ),
    ]
