# Generated by Django 4.0.1 on 2022-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_message_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='modified',
        ),
        migrations.AddField(
            model_name='ticket',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
