# Generated by Django 4.0.1 on 2022-01-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_remove_message_modified_ticket_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='modified',
        ),
    ]
