---

 - hosts: hosts
   become: true
   tasks:
   - name: Clone github repository
     git:
       repo: git@gitlab-server.local:admin-main/final-project.git
       dest: $PWD/python-app/
       clone: yes
       update: yes
